apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-udp-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: shared_key  

spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.2
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53  
