kind: Pod
apiVersion: v1
metadata:
  name: otus
spec:
  containers:
    - name: app
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: data-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: storage-pvc