kind: Pod
apiVersion: v1
metadata:
  name: storage-pod-restored
spec:
  containers:
    - name: app
      image: bash
      volumeMounts:
      - mountPath: "/data"
        name: data-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: storage-pvc-resored
