kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kit
subjects:
- kind: ServiceAccount
  name: kit
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kit
  apiGroup: rbac.authorization.k8s.io