 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kit
rules:
- apiGroups:
  - '*'
  resources:
  - 'pods'
  verbs:
  - 'get'
  - 'watch'
  - 'list'
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - 'update'
  - 'patch'
  - 'create'