server:
  extraEnvironmentVars:
    VAULT_ADDR: https://localhost:8200
    VAULT_CACERT: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  extraVolumes:
    - type: secret
      name: vault-certs
      path: null # /vault/userconfig
  standalone:
    enabled: false
  ha:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-certs/tls.crt"
        tls_key_file  = "/vault/userconfig/vault-certs/tls.key"      
      }
      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }
ui:
  enabled: true
  serviceType: "ClusterIP"