{
 "title": "test_nginx",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Writing  connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_writing{namespace=~\"default\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waiting  connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_waiting{namespace=~\"default\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reading  connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_reading{namespace=~\"default\"}[1m])) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Handled connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_handled{namespace=~\"default\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Conncetions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{namespace=~\"default\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Accepted connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted{namespace=~\"default\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}