apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    prometheus: default
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - protocol: TCP
      port: 9113
      targetPort: 9113
      name: metrics
