repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress
    chart: stable/nginx-ingress
    namespace: nginx-ingress
    version: 1.11.1

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: 0.9.0
    values:
      - "../cert-manager/values.yaml"

  - name: chartmuseum
    chart: stable/chartmuseum
    namespace: chartmuseum
    version: 2.3.2
    values:
      - "../chartmuseum/values.yaml"

  - name: harbor
    chart: harbor/harbor
    namespace: harbor
    version: 1.1.2
    values:
      - "../cert-manager/values.yaml"