backend:
  type: es
  es:
    host: elasticsearch-master

tolerations:
  - operator: "Exists"

rawConfig: |
  @INCLUDE fluent-bit-service.conf
  @INCLUDE fluent-bit-input.conf
  @INCLUDE fluent-bit-filter.conf
  @INCLUDE fluent-bit-output.conf
  [FILTER]
    Name modify
    Match *
    Remove time
    Rename @timestamp orig_timestamp
