#--- DOCKER ---
- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest 
    update_cache: yes
    force_apt_get: yes

- name: Install required system packages
  apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install container.d
  apt: 
    update_cache: yes 
    name: containerd.io=1.2.13-1
    state: present

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes 
    name: docker-ce=5:19.03.8~3-0~ubuntu-bionic
    state: present

- name: Update apt and install docker-ce-cli
  apt: 
    update_cache: yes 
    name: docker-ce-cli=5:19.03.8~3-0~ubuntu-bionic
    state: present

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Copy docker config file with owner and permissions
  copy:
    src: ../files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Create a directory if it does not exist
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
  notify: restart docker
