#--- ROUTING ---
- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Set net.bridge.bridge-nf-call-iptables  on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.bridge.bridge-nf-call-iptables 
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Set net.bridge.bridge-nf-call-ip6tables on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
